In [ ]:
#File Handling & CSVs
#1. Reading a Text File
#Write a Python script that opens a file in read mode and prints its
#contents. Use any .txt file for practice.

In [3]:
# Reading a Text File in Python

# Open the file in read mode
with open("TDI WEEK 3 txt file") as file:
    # Read the contents of the file
    contents = file.read()
    # Print the contents
    print(contents)

Hello TDI Student, are you ready for week 2


In [ ]:
#Writing to a File
#Create a Python script that writes the string "Hello, Data Analysis!" to anew text file.


In [4]:
# Writing to a Text File in Python

# Open (or create) the file in write mode
with open("TDI WEEK 3 output.txt", "w") as file:
    # Write the string into the file
    file.write("Hello, Data Analysis!")

print("File created and text written successfully!")


File created and text written successfully!


In [ ]:
#Reading the Titanic Dataset (CSV)
#Use the csv module to read the Titanic dataset (titanic.csv). Print the first 5 rows of the dataset.

In [5]:
# Reading the Titanic dataset with csv module

import csv

# Open the Titanic dataset
with open("TDI python week3 dataset(Titanic Analysis).csv", mode="r") as file:
    csv_reader = csv.reader(file)
    
    # Convert the reader to a list so we can slice rows
    rows = list(csv_reader)
    
    # Print the first 5 rows
    for row in rows[:5]:
        print(row)


['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket', 'fare', 'cabin', 'embarked', 'boat', 'body', 'home.dest']
['1', '1', 'Allen, Miss. Elisabeth Walton', 'female', '29', '0', '0', '24160', '211.3375', 'B5', 'S', '2', '', 'St Louis, MO']
['1', '1', 'Allison, Master. Hudson Trevor', 'male', '0.9167', '1', '2', '113781', '151.55', 'C22 C26', 'S', '11', '', 'Montreal, PQ / Chesterville, ON']
['1', '0', 'Allison, Miss. Helen Loraine', 'female', '2', '1', '2', '113781', '151.55', 'C22 C26', 'S', '', '', 'Montreal, PQ / Chesterville, ON']
['1', '0', 'Allison, Mr. Hudson Joshua Creighton', 'male', '30', '1', '2', '113781', '151.55', 'C22 C26', 'S', '', '135', 'Montreal, PQ / Chesterville, ON']


In [ ]:
#Counting Records
#After reading the Titanic CSV file, count the total number of passengers.

In [6]:
import csv

# Open the Titanic dataset
with open("TDI python week3 dataset(Titanic Analysis).csv", mode="r") as file:
    csv_reader = csv.reader(file)
    
    # Skip the header
    header = next(csv_reader)
    
    # Count the rows (passengers)
    passenger_count = sum(1 for row in csv_reader)

print("Total number of passengers:", passenger_count)


Total number of passengers: 1309


In [ ]:
#Calculating Average Fare
#Write a script to calculate the average fare paid by passengers using the Titanic dataset.

In [9]:
# Calculating the average fare from Titanic dataset

import csv

with open("TDI python week3 dataset(Titanic Analysis).csv", mode="r") as file:
    csv_reader = csv.DictReader(file)  # Use DictReader so we can access by column names
    
    total_fare = 0.0
    passenger_count = 0
    
    for row in csv_reader:
        if row["fare"]:  # Make sure the value isn’t empty
            total_fare += float(row["fare"])
            passenger_count += 1
    
    # Calculate average fare
    average_fare = total_fare / passenger_count if passenger_count > 0 else 0

print(f"Average fare paid by passengers: {average_fare:.2f}")


Average fare paid by passengers: 33.30


In [ ]:
#Survivors by Class
#Write a Python script to calculate the number of survivors per passenger class (1st, 2nd, and 3rd class).


In [10]:
import csv

# Open the Titanic dataset
with open("TDI python week3 dataset(Titanic Analysis).csv", mode="r") as file:
    csv_reader = csv.DictReader(file)  # Use DictReader to access columns by name
    
    # Dictionary to store survivors per class
    survivors_by_class = {"1": 0, "2": 0, "3": 0}
    
    # Loop through each row
    for row in csv_reader:
        if row["survived"] == "1":  # Check if passenger survived
            pclass = row["pclass"]  # Get passenger class
            survivors_by_class[pclass] += 1  # Increment survivor count for that class
    
    # Print results
    for pclass, count in survivors_by_class.items():
        print(f"Survivors in Class {pclass}: {count}")


Survivors in Class 1: 200
Survivors in Class 2: 119
Survivors in Class 3: 181


In [ ]:
#Introduction to NumPy
#7. NumPy Basics
#Import the NumPy library and create a 1D array containing the following numbers: [10, 15, 20, 25]. Print the array.


In [11]:
# NumPy Basics

import numpy as np  

# Create a 1D NumPy array  
arr = np.array([10, 15, 20, 25])  

# Print the array  
print(arr)


[10 15 20 25]


In [ ]:
#8. Array Operations
#Using the array from the previous question, perform the followingoperations:
#• Multiply each element by 2.
#• Subtract 5 from each element

In [12]:
import numpy as np

# Original array
arr = np.array([10, 15, 20, 25])

# Multiply each element by 2
multiplied = arr * 2

# Subtract 5 from each element
subtracted = arr - 5

# Print results
print("Original Array:", arr)
print("Multiplied by 2:", multiplied)
print("Subtracted 5:", subtracted)


Original Array: [10 15 20 25]
Multiplied by 2: [20 30 40 50]
Subtracted 5: [ 5 10 15 20]


In [ ]:
#2D Array Creation
#Create a 2D NumPy array with shape (3, 3) using the following data:
#• First row: 1, 2, 3
#• Second row: 4, 5, 6
#• Third row: 7, 8, 9

In [13]:
import numpy as np

# Create the 2D array
arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(arr_2d)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#Titanic Data with NumPy
#Convert the Fare column of the Titanic dataset to a NumPy array and
#calculate:
#• The minimum fare.
#• The maximum fare.
#• The mean fare.

In [15]:
import csv
import numpy as np

# Read Titanic dataset and extract 'fare' column
fares = []
with open("TDI python week3 dataset(Titanic Analysis).csv", "r") as file:
    csv_reader = csv.DictReader(file)
    for row in csv_reader:
        if row["fare"]:  # check if not empty
            fares.append(float(row["fare"]))

# Convert to NumPy array
fare_array = np.array(fares)

# Calculate statistics
min_fare = np.min(fare_array)
max_fare = np.max(fare_array)
mean_fare = np.mean(fare_array)

print("Minimum Fare:", round(min_fare, 2))
print("Maximum Fare:", round(max_fare, 2))
print("Mean Fare:", round(mean_fare, 2))

Minimum Fare: 0.0
Maximum Fare: 512.33
Mean Fare: 33.3


In [ ]:
#Array Indexing
#Use array indexing to extract the first row and first column of the 2D array created earlier. Print the results.

In [16]:
import numpy as np

# Create the 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Extract first row
first_row = arr[0]      # row index 0
# Extract first column
first_col = arr[:, 0]   # all rows, column index 0

print("First Row:", first_row)
print("First Column:", first_col)


First Row: [1 2 3]
First Column: [1 4 7]


In [ ]:
#Random Array
#Create a NumPy array with 10 random numbers between 0 and 1. Print the array and find the maximum value

In [17]:
import numpy as np

# Create array with 10 random numbers between 0 and 1
random_array = np.random.rand(10)

# Find maximum value
max_value = np.max(random_array)

print("Random Array:", random_array)
print("Maximum Value:", max_value)


Random Array: [0.24030281 0.39163795 0.21401355 0.87563743 0.21104785 0.65419502
 0.23824616 0.25196151 0.57283692 0.70249191]
Maximum Value: 0.8756374279126221


In [ ]:
#Survivor Analysis with NumPy
#• Use the Titanic dataset and convert the Survived column to a NumPy array.
#• Calculate the percentage of passengers who survived

In [18]:
import csv
import numpy as np

# Read Titanic dataset and extract 'survived' column
survived = []
with open("TDI python week3 dataset(Titanic Analysis).csv", "r") as file:
    csv_reader = csv.DictReader(file)
    for row in csv_reader:
        if row["survived"]:  # check if not empty
            survived.append(int(row["survived"]))

# Convert to NumPy array
survived


[1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
